[package]
name = "STT-grpc"
version = "0.1.0"
authors = ["artemiy.bezukladnikov <abe@datacorp.ee>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
